using System.Text.Json;
using System.Text.Json.Nodes;
using Navi_Protocol;
using Navi_ServiceSdk;

namespace Navi_LMStudioNode.Services;

public sealed class Respond : Service
{
    private readonly LmStudioClient _client;
    private readonly ILogger<Respond> _logger;
    private readonly LmStudioNode _node;

    internal Respond(
        LmStudioNode node,
        LmStudioClient client,
        ILogger<Respond> logger)
    {
        _node = node;
        _client = client;
        _logger = logger;
    }

    public static ServiceDescription Description { get; } = new()
    {
        ServiceName = "LMStudio.Respond",
        Summary = "Generates a response using LM Studio.",
        Parameters =
        [
            new ServiceParameterDescription
            {
                Name = "prompt",
                Summary = "The text prompt to send to LM Studio.",
                ParameterType = ServiceValueType.String
            }
        ],
        ReturnValues =
        [
            new ServiceReturnValueDescription
            {
                Name = "response",
                Summary = "The text generated by LM Studio.",
                ReturnType = ServiceValueType.String
            }
        ]
    };

    public override ServiceDescription ServiceDescription => Description;

    public override async Task<ServiceResponse> RunAsync(ServiceRequest serviceRequest)
    {
        if (!TryGetPrompt(serviceRequest, out string? prompt))
        {
            return Failure(
                "invalid_prompt",
                "The required 'prompt' parameter must be a non-empty string.",
                recoverable: false);
        }

        try
        {
            if (string.IsNullOrWhiteSpace(_node.ModelInstanceId))
            {
                return Failure(
                    "lm_studio_not_ready",
                    "The LM Studio model is not ready for inference.",
                    recoverable: true);
            }

            Contracts.ChatResponse result = await _client.ChatAsync(
                _node.ModelInstanceId,
                prompt!,
                maxOutputTokens: null,
                CancellationToken.None);

            string generatedText = string.Join(
                Environment.NewLine,
                result.Output
                    .Where(item => item.Type == "message")
                    .Select(item => item.Content)
                    .Where(content => !string.IsNullOrWhiteSpace(content)));

            if (string.IsNullOrWhiteSpace(generatedText))
            {
                _logger.LogWarning("LM Studio returned a response without generated text.");
                return Failure(
                    "lm_studio_response_invalid",
                    "LM Studio returned no generated text.",
                    recoverable: true);
            }

            return new ServiceResponse
            {
                Status = Navi_Protocol.TaskStatus.Success,
                ReturnValues = new JsonObject
                {
                    ["response"] = generatedText
                }
            };
        }
        catch (Exception exception) when (
            exception is HttpRequestException or JsonException)
        {
            _logger.LogError(exception, "The LM Studio response request failed.");
            return Failure(
                "lm_studio_request_failed",
                "LM Studio could not complete the request.",
                recoverable: true);
        }
    }

    private static bool TryGetPrompt(ServiceRequest request, out string? prompt)
    {
        prompt = null;
        return request.Parameters.TryGetPropertyValue("prompt", out JsonNode? promptNode) &&
               promptNode is JsonValue promptValue &&
               promptValue.TryGetValue(out prompt) &&
               !string.IsNullOrWhiteSpace(prompt);
    }

    private static ServiceResponse Failure(
        string code,
        string message,
        bool recoverable)
    {
        return new ServiceResponse
        {
            Status = Navi_Protocol.TaskStatus.Failed,
            Errors =
            [
                new ServiceError
                {
                    Code = code,
                    Message = message,
                    Recoverable = recoverable
                }
            ]
        };
    }
}
