AllowedHosts = "*"

[Hub]
BaseUrl = "http://localhost:5000"

[Node]
Name = "LM Studio"
Address = "http://localhost:5003"

[LmStudio]
BaseUrl = "http://localhost:1234"
Model = "openai-gpt-oss-20b-heretic-uncensored-neo-imatrix"
ContextLength = 8192

[Logging.LogLevel]
Default = "Information"
"Microsoft.AspNetCore" = "Warning"
"System.Net.Http.HttpClient" = "Warning"
